##########################################################################################
# GENERATE vignettes/code_rwf.R
##########################################################################################
# Builds a standalone vignettes/code_rwf.R that contains the rwf functions used by the
# vignettes, so documents can be deployed (rsconnect/renv) without the rwf package.
# In a vignette replace library(rwf) with source(paste0(directory,"code_rwf.R"))
# Re-run this script whenever the package functions or the vignettes change.
##########################################################################################
directory<-if (requireNamespace("rstudioapi",quietly=TRUE) && rstudioapi::isAvailable())
  paste0(dirname(rstudioapi::getActiveDocumentContext()$path),"/") else paste0(getwd(),"/")
dir_package<-paste0(directory,"rwf/")
dir_vignettes<-paste0(directory,"vignettes/")
output_file<-paste0(dir_vignettes,"code_rwf.R")
data_url<-"https://raw.githubusercontent.com/sedzinfo/rwf/main/rwf/data/"
##########################################################################################
# PACKAGE FUNCTIONS WITH THEIR SOURCE
##########################################################################################
tokens<-function(text) unique(unlist(regmatches(text,gregexpr("[A-Za-z.][A-Za-z0-9._]*",text))))
functions_source<-list()
for (f in list.files(paste0(dir_package,"R"),pattern="\\.R$",full.names=TRUE)) {
  expressions<-parse(f,keep.source=TRUE)
  sources<-attr(expressions,"srcref")
  for (i in seq_along(expressions)) {
    e<-expressions[[i]]
    if (is.call(e) && as.character(e[[1]]) %in% c("<-","=") && is.call(e[[3]]) &&
        identical(e[[3]][[1]],as.name("function")))
      functions_source[[as.character(e[[2]])]]<-paste(as.character(sources[[i]]),collapse="\n")
  }
}
functions_source<-lapply(functions_source,function(x) gsub("rwf::","",x,fixed=TRUE))
package_functions<-names(functions_source)
##########################################################################################
# FUNCTIONS USED BY THE VIGNETTES (INCLUDING THEIR INTERNAL DEPENDENCIES)
##########################################################################################
chunk_code<-function(file) {
  lines<-readLines(file,warn=FALSE)
  start<-grep("^\\s*```\\s*\\{r",lines)
  end<-grep("^\\s*```\\s*$",lines)
  code<-c()
  for (s in start) {
    e<-end[end>s][1]
    if (!is.na(e) && e>s+1) code<-c(code,lines[(s+1):(e-1)])
  }
  code
}
vignettes<-list.files(dir_vignettes,pattern="\\.[Rr]md$",full.names=TRUE)
used<-intersect(tokens(unlist(lapply(vignettes,chunk_code))),package_functions)
repeat {
  dependencies<-intersect(tokens(unlist(functions_source[used])),package_functions)
  if (all(dependencies %in% used)) break
  used<-union(used,dependencies)
}
used<-package_functions[package_functions %in% used]
##########################################################################################
# IMPORTS FROM NAMESPACE NEEDED BY THE SELECTED FUNCTIONS
##########################################################################################
attached_by_default<-c("base","stats","utils","graphics","grDevices","methods","datasets")
namespace<-parseNamespaceFile("rwf",substr(directory,1,nchar(directory)-1))
import_map<-c()
for (imp in namespace$imports) {
  pkg<-imp[[1]]
  if (pkg %in% attached_by_default) next
  objects<-if (length(imp)==1) getNamespaceExports(pkg) else imp[[2]]
  import_map[objects]<-pkg
}
used_symbols<-unique(unlist(lapply(functions_source[used],function(x) {
  c(all.names(parse(text=x,keep.source=FALSE)),tokens(x))
})))
imports<-import_map[names(import_map) %in% used_symbols & !names(import_map) %in% used]
imports<-imports[order(imports,names(imports))]
datasets<-sub("\\.rda$","",list.files(paste0(dir_package,"data"),pattern="\\.rda$"))
##########################################################################################
# WRITE FILE
##########################################################################################
header<-c(
  "##########################################################################################",
  "# RWF FUNCTIONS FOR PUBLISHING",
  "# Generated by generate_code_rwf.R from the rwf package source. Do not edit by hand.",
  "# source(\"code_rwf.R\") replaces library(rwf) so documents deploy without the package.",
  "##########################################################################################",
  "library(ggplot2)",
  "if (\"rwf_functions\" %in% search()) detach(\"rwf_functions\")",
  ".rwf_imports<-new.env(parent=globalenv())")
# delayedAssign loads a package only when a function that needs it is called
import_lines<-sprintf("delayedAssign(\"%s\",%s::`%s`,assign.env=.rwf_imports)",
                      names(imports),imports,names(imports))
data_lines<-c(
  "##########################################################################################",
  "# DATA",
  "##########################################################################################",
  paste0(".rwf_datasets<-c(",paste0("\"",datasets,"\"",collapse=","),")"),
  paste0(".rwf_data_url<-\"",data_url,"\""),
  "data<-function(...,list=character(),envir=parent.frame()) {",
  "  requested<-c(vapply(as.list(substitute(list(...)))[-1L],as.character,\"\"),list)",
  "  if (length(requested)==0 || !all(requested %in% .rwf_datasets)) {",
  "    call<-match.call()",
  "    call[[1]]<-quote(utils::data)",
  "    return(eval(call,parent.frame()))",
  "  }",
  "  for (dataset in requested) {",
  "    local_files<-file.path(c(\"../rwf/data\",\"rwf/data\",\"data\"),paste0(dataset,\".rda\"))",
  "    file<-local_files[file.exists(local_files)][1]",
  "    if (is.na(file)) {",
  "      file<-tempfile(fileext=\".rda\")",
  "      utils::download.file(paste0(.rwf_data_url,dataset,\".rda\"),file,mode=\"wb\",quiet=TRUE)",
  "    }",
  "    load(file,envir=envir)",
  "  }",
  "  invisible(requested)",
  "}")
body<-c(
  header,import_lines,
  ".rwf<-new.env(parent=.rwf_imports)",
  "local({",
  data_lines,
  "##########################################################################################",
  "# FUNCTIONS",
  "##########################################################################################",
  unlist(lapply(used,function(x) c(functions_source[[x]],""))),
  "},envir=.rwf)",
  "attach(.rwf,name=\"rwf_functions\",warn.conflicts=FALSE)",
  "rm(.rwf,.rwf_imports)")
writeLines(body,output_file)
cat("Wrote",output_file,"\n",
    length(used),"functions,",length(imports),"imports from",
    paste(sort(unique(imports)),collapse=", "),"\n")
